spring.application.name=restClient
logging.level.com.example.restClient=Debug

spring.datasource.url=jdbc:mysql://localhost:3306/mydb
spring.datasource.username=root
spring.datasource.password=1234567890

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.issuer=divasnhu
jwt.expiry=900
jwt.secret=b3d2dx+nWyBgViwLOeOekqTD6sMR5wYJu5W7oa/lbIk=